### ISSUE TITLE
LED Alignment

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#10]
## Task Description

**Brief description:**
Provide LED light patterns that show the drive team whether the robot is aligned properly for autonomous. After a path is selected, if the pose estimator doesn't determine that the robot is in the correct starting location (or at least close to it), the lights on the robot should guide the drive team on how to fix the position.

**Comment by JosephTLockwood** [comment]
This will not be possible due to the trust value of vision being so low.
