### ISSUE TITLE
Use auto alignment in autonomous paths

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#21]
## Task Description

**Brief description:**
Instead of just following a preset path, we can use the commands used in #20 and #17 to aim at game pieces and the speaker automatically, no matter what. This should provide more consistency.

## Task Details

**To-Do:**
- [ ] Add event markers to paths to have robot use object detection for game pieces
- [ ] Add event markers to paths to aim at speaker

**Comment by JosephTLockwood** [comment]
Example here of how to attempt https://pathplanner.dev/pplib-override-target-rotation.html

**Comment by JosephTLockwood** [comment]
Will no longer be implementing. Will either preset or use shoot while moving
