### ISSUE TITLE
Get Eos Running

### ISSUE THREAD

**Issue by JosephTLockwood** [Hemlock5712/2024-Robot#27]
Get Eos running. It will require an update of all motors, encoders, and robotics. It also will require an update of all PID values for Falcons. Use this base code. You do not have to do subsystems in the IO manner if you want.

**Comment by JosephTLockwood** [comment]
Instructions in ReadMe. Wiki is planned at some point but will not be available for this.

**Comment by alexhaltom** [comment]
Do you mean Eos?

**Comment by CrispyBacon1999** [comment]
That's what I'm assuming as well

**Comment by GavinGilber** [comment]
We updated the CTRE motor controllers and REV robotics motor controllers.

**Comment by GavinGilber** [comment]
We checked the roboRIO and it's up to date for 2024.

**Comment by JosephTLockwood** [comment]
@GavinGilber I would double check. Did you update it last night? I think the last time we updated it we used a 2024 beta version, so it may show as 2024 but not be the up-to-date version.

**Comment by alexhaltom** [comment]
This item will be paused as the RoboRio 2.0 is going to be pulled for the competition robot. We can resume once a RoboRio 1 is installed.
