### ISSUE TITLE
Implement IO With Motors Fully

### ISSUE THREAD

**Issue by TimR26** [Hemlock5712/2024-Robot#37]
Intake (2 neos)
Make a wrist IO and subsystem (1 neo)
Shooter/Flywheel Two krakens

**Comment by JosephTLockwood** [comment]
This is an attempt to lay out conditions when certain things are happing.

**_Subsystems_**
| Subsystems| Condition 1| Condition 2| Condition 3|
|--------|--------|--------|--------|
| Intake| `hasGamePiece and isLoadPosition` run game piece until `isLoaded` | `hasGamePiece` Don't lower fully| `(isLoaded or isOverLoaded) and hasGamePieceIntake` lower intake and reverse|
| Magazine| `isOverLoaded` reverse until  `isLoaded`| Only Shoots when `isAligned` | |
| Shooter|  `isOverLoaded` reverse until  `isLoaded`| Only Shoots when `isAligned` | |
| Arm| `isWristInPosition` Move after wrist is in position| `isLoaded or isOverLoaded` can move to shoot position| |
|Wrist| `isLoaded or isOverLoaded` can move to shoot position| |
|Sensors| Needs `isLoaded`, `hasGamePiece` and `isOverLoaded` coded| |
|Drive| Needs `isAligned` coded| | |

**_States_**
| States|When State Occurs|
|--------|--------|
| `isLoaded`|Game Piece in middle shooter sensor (only look at shooter sensors)|
|`hasGamePieceIntake`| Has game piece triggering intake sensor|
| `hasGamePiece`| Game piece is triggering any sensor|
|`isOverLoaded`| Game piece is triggering far sensor|
|`isLoadPosition`| `isWristInPosition` and `isArmInPosition` are in `True`|
|`isWristInPosition`| If the wrist is at the set position|
|`isArmInPosition`| If the arm is at the set position|
|`isAligned`| Position of drive is facing target|


Let me know if there are any others I can edit this. Other that potentially will need is climbing states and conditions.
