### ISSUE TITLE
Arm Hoot files

### ISSUE THREAD

**Issue by JosephTLockwood** [Hemlock5712/2024-Robot#55]
[rio_2024-02-23_16-33-27.zip](https://github.com/Hemlock5712/2024-Robot/files/14390321/rio_2024-02-23_16-33-27.zip)

@CoryNessCTR

**Comment by JosephTLockwood** [comment]
[rio_2024-01-04_22-22-52.zip](https://github.com/Hemlock5712/2024-Robot/files/14390398/rio_2024-01-04_22-22-52.zip)

**Comment by CrispyBacon1999** [comment]
![PXL_20240223_220252873.MP.jpg](https://github.com/Hemlock5712/2024-Robot/assets/6081500/2e64166c-bb3b-4436-8d61-0b047d25f063)

![PXL_20240223_220258813.jpg](https://github.com/Hemlock5712/2024-Robot/assets/6081500/9e7abe40-7a42-4b66-84df-6c23657b88e0)

**Comment by TimR26** [comment]
[Talon FX Self Test Response.zip](https://github.com/Hemlock5712/2024-Robot/files/14454769/Talon.FX.Self.Test.Response.zip)
@CoryNessCTR here's the self test responses from that motor (no load). When in reverse, the motor squeals as if it's stalling and gets super hot. When forward, the motor runs fine.
