### ISSUE TITLE
Update vendor dependencies to 2024 (stable)

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#8]
## Task Description

**Brief description:**
We need to upgrade all the dependencies to the stable versions of the 2024 libraries. Currently we're still running 2024 beta, which is missing some key features (namely april tag locations).

**Related feature/issue:**
- Waiting on [new version of AdvantageKit](https://github.com/Mechanical-Advantage/AdvantageKit/releases) to be able to update

## Task Details

**To-Do:**
- [ ] WPILib
  - [ ] AdvantageKit
  - [ ] Phoenix 6
  - [ ] RevLib
  - [ ] Pathplanner

**Additional Information:**
Most of this can be done with a simple `WPILib: Manage Vendor Libraries → Check for updates (online)`

**Comment by JosephTLockwood** [comment]
This should be solved when the template is merged in.
