### ISSUE TITLE
Drive - Run robot characterizations

### ISSUE THREAD

**Issue by CrispyBacon1999** [Hemlock5712/2024-Robot#9]
## Task Description

**Brief description:**
Use either sysID or the robot characterization script in the project to determine appropriate gains for the drivetrain

**Comment by JosephTLockwood** [comment]
Please have a look here for more details. We will have several other tasks to run to have accurate robot characterization. 

https://docs.google.com/presentation/d/1rxLvOsYmhuwOqGz5Vzk3h6-8su6OSUx0ynlrUEr7pcw/edit?usp=sharing

![Image](https://github.com/Hemlock5712/2024-Robot/assets/56933815/2c319d07-657d-4e51-9362-e8677c5d88e5)
